For the modulo classes $\mathbb{Z}_n$ Show that $a^n\cdot b^n \equiv (a\cdot b)^n$  
In modulo $x\in\mathbb{N}$ arithmetic, $a^{n}=(n\cdot a)\mod x$,
therefore, we need to show that 
$$
\left[\big(\left(n\cdot a\right)\bmod x\big)+\big(\left(n\cdot b\right)\bmod x\big)\right]\bmod x=\left(n\cdot a+n\cdot b\right)\bmod x.$$


In [20]:

from numpy import *
def ex1(a,b,n,x):
    r=(n*a+n*b)%x
    return r

def ex(a,b,n,x):
    r=((n*a)%x+(n*b)%x)%x
    return r
x=6;
S=linspace(0,x-1,(x-1)*(x-1),dtype=int)
S1=linspace(0,x-1,(x-1)*(x-1),dtype=int)
n=2; cnt=0;
for a in range(x-1):
    for b in range(x-1):
        S[cnt]=ex(a,b,n,x)
        S1[cnt]=ex1(a,b,n,x)
        cnt=cnt+1
print(S)
print(S1)

[0 2 4 0 2 2 4 0 2 4 4 0 2 4 0 0 2 4 0 2 2 4 0 2 4]
[0 2 4 0 2 2 4 0 2 4 4 0 2 4 0 0 2 4 0 2 2 4 0 2 4]


Let $a\in\mathbb{Z}_x$ which are the x integer remainder classes modulo $x, x\in\mathbb{N}$
Show that $a^{n+m}=a^na^m$ for $(n,m)\in\mathbb{N}$.<br>  In modulo $x\in\mathbb{N}$ arithmetic, $a^{n}=(n\cdot a)\bmod x$,
therefore, we need to show that $$\left(n\times a\right)\bmod x+\left(m\times a\right)\bmod x=\big((n+m)\times a\big)\bmod x.$$  

In [28]:
from numpy import *
def exL(m,n,a,x):
    r=((n*a)%x+(m*a)%x)%x
    return r

def exR(m,n,a,x):
    r=((n+m)*a)%x
    return r
x=6;
S=linspace(0,x-1,(x-1)*(x-1),dtype=int)
S1=linspace(0,x-1,(x-1)*(x-1),dtype=int)
a=5; cnt=0;
for m in range(x-1):
    for n in range(x-1):
        S[cnt]=exL(m,n,a,x)
        S1[cnt]=exR(m,n,a,x)
        cnt=cnt+1
print(S)
print(S1)

[0 5 4 3 2 5 4 3 2 1 4 3 2 1 0 3 2 1 0 5 2 1 0 5 4]
[0 5 4 3 2 5 4 3 2 1 4 3 2 1 0 3 2 1 0 5 2 1 0 5 4]
