<font size=3>
Here we use the Euclidean algorithm to find the greatest common divisor (gcd) of two polynomials.

In [64]:
%reset -f 
from sympy import * 
from IPython import display
#import numpy as np
#import matplotlib.pyplot as plt
#%matplotlib inline
init_printing(use_latex='mathjax')

x = Symbol('x')

def gcd_poly(a,b):
    q,r = div(a,b,domain='QQ')
    a=g
    b=r
    return a,b

g = 3*x**4 - 5*x**3 - 4*x**2 + 11*x - 5
f = x**5 + x**4 - 12*x**3 + 20*x**2 - 13*x + 3
  
# Using sympy.div() method 
while g!=0:
    f,g = gcd_poly(f,g) 
    print('f =')
    display.display(f)
    print('g =')
    display.display(g)
print('Ergo: GCD = ',f)


f =


   4      3      2           
3⋅x  - 5⋅x  - 4⋅x  + 11⋅x - 5

g =


      3        2             
  56⋅x    179⋅x    190⋅x   67
- ───── + ────── - ───── + ──
    9       9        9     9 

f =


      3        2             
  56⋅x    179⋅x    190⋅x   67
- ───── + ────── - ───── + ──
    9       9        9     9 

g =


      2                
1539⋅x    1539⋅x   1539
─────── - ────── + ────
  3136     1568    3136

f =


      2                
1539⋅x    1539⋅x   1539
─────── - ────── + ────
  3136     1568    3136

g =


0

Ergo: GCD =  1539*x**2/3136 - 1539*x/1568 + 1539/3136


In [61]:
display.display(3136*f/1539)

 2          
x  - 2⋅x + 1

In [54]:
%reset -f 
from sympy import * 
from IPython import display
import numpy as np
#import matplotlib.pyplot as plt
#%matplotlib inline
init_printing(use_latex='mathjax')

x = Symbol('x')
f=((x-1)**3*(x**2+4*x-3))
display.display(f)
f=expand(f)
display.display(f)

       3 ⎛ 2          ⎞
(x - 1) ⋅⎝x  + 4⋅x - 3⎠

 5    4       3       2           
x  + x  - 12⋅x  + 20⋅x  - 13⋅x + 3

<font size=3>
The code below will fetch coefficients from a polynomial.
If we divide through by the leading coefficient, we get a monic polynomial.

In [74]:
%reset -f 
from sympy import * 
from IPython import display
import numpy as np
#import matplotlib.pyplot as plt
#%matplotlib inline
init_printing(use_latex='mathjax')

# yields the coefficients from highest to lowest degree
def extract_coefficients(p, degree):
    n = degree + 1
    sample_x = [ x for x in range(n) ]
    sample_y = [ p(x) for x in sample_x ]
    A = [ [ 0 for _ in range(n) ] for _ in range(n) ]
    for line in range(n):   
        for column in range(n):
            A[line][column] = sample_x[line] ** column
    c = np.linalg.solve(A, sample_y)
    return c[::-1]

h=extract_coefficients(lambda x: 1539*x**2/3136 - 1539*x/1568 + 1539/3136,2)
display.display(h)
print(h/h[0])

array([ 0.49075255, -0.9815051 ,  0.49075255])

[ 1. -2.  1.]
