<font size="3">
<h1>Adjacency List</h1>
<ol>
<li>Make an adjacency list for a random "connected" simple graph with a limit to the maximum degree of any vertex.  How can we be sure that it is connected?</li>
    <li>Number the vertices from 0 to n-1.</li>
    <li>Randomly choose other vertices to have an edge between them.</li>
    <li>If node 0 is adj to node 1, then it must be that node 1 is adj to node 0. Make this true
    </ol>
    <h2>Alternative</h2>
    This turns out to be rather dificult to do.  The Goal is to find the number of graphs on $n$ unlabeled nodes. A000088. There is a website to do this up to n=20.
    
  <a href="http://combos.org/nauty">http://combos.org/nauty</a>
    

In [65]:
import numpy as np
import random
def pickelements(List,num2pick):
    return random.sample(List,num2pick)


#n will be the number of vertices in the graph
n=5
#d will be the number of degrees at each vertex
d=2

L=np.zeros(shape=(n,d+1),dtype=int16) #Initialize the adjacency list as a numpy array
for i in range(n):
    L[i,0]=i

for i in range(n):
    K=list(range(n));  #this produces a list from 0 to n
    K.pop(i);          #removes the ith element and repacks it.
    a,b = pickelements(K,d) #a,b,c,... have to be as many and the degree. no less, no more
    L[i,1]=a
    L[i,2]=b
#     L[i,3]=c
    
print(L)

[[0 2 3]
 [1 3 0]
 [2 4 1]
 [3 1 0]
 [4 1 2]]


In [2]:
import random

l = [0, 1, 2, 3, 4]
for i in range(10):
    print(random.sample(l, 2))

[4, 3]
[2, 3]
[0, 1]
[4, 2]
[4, 2]
[2, 3]
[1, 0]
[4, 2]
[2, 1]
[0, 3]


<font size="3">
for the next cell, see<br>
  <a href="https://www.programiz.com/dsa/graph-adjacency-list">https://www.programiz.com/dsa/graph-adjacency-list</a>
    <br><br>
    Also this site on linked lists is helpful:<br>
    <a href="https://realpython.com/linked-lists-python/#:~:text=Linked%20lists%20are%20an%20ordered,part%20of%20their%20own%20elements">https://realpython.com/linked-lists-python/#:~:text=Linked%20lists%20are%20an%20ordered,part%20of%20their%20own%20elements.</a>

In [6]:

print(graph)
# Adjascency List representation in Python


class AdjNode:
    def __init__(self, value):
        self.vertex = value
        self.next = None


class Graph:
    def __init__(self, num):
        self.V = num
        self.graph = [None] * self.V

    # Add edges
    def add_edge(self, s, d):
        node = AdjNode(d)
        node.next = self.graph[s]
        self.graph[s] = node

        node = AdjNode(s)
        node.next = self.graph[d]
        self.graph[d] = node

    # Print the graph
    def print_agraph(self):
        for i in range(self.V):
            print("Vertex " + str(i) + ":", end="")
            temp = self.graph[i]
            while temp:
                print(" -> {}".format(temp.vertex), end="")
                temp = temp.next
            print(" \n")


if __name__ == "__main__":
    V = 5

    # Create graph and edges
    graph = Graph(V)
    graph.add_edge(0, 1)
    graph.add_edge(0, 2)
    graph.add_edge(0, 3)
    graph.add_edge(1, 2)

    graph.print_agraph()

Vertex 0: -> 3 -> 2 -> 1 

Vertex 1: -> 2 -> 0 

Vertex 2: -> 1 -> 0 

Vertex 3: -> 0 

Vertex 4: 

